# Data Frame containing geographical coordinates

In [10]:
import pandas as pd

In [19]:
new_df = pd.read_csv('/resources/labs/DP0701EN/dffinout.csv', keep_default_na=False, na_values=[""])

In [20]:
new_df

,PostalCode,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [4]:
gc = pd.read_csv('Geospatial_Coordinates (1).csv')

In [5]:
gc.set_index("PostalCode", inplace=True)

In [6]:
gc1 = gc.loc[['M5G', 'M2H'], ['Latitude', 'Longitude']]
gc2 = gc.loc[['M4B', 'M1J'], ['Latitude', 'Longitude']]
gc3 = gc.loc[['M4G', 'M4M'], ['Latitude', 'Longitude']]
gc4 = gc.loc[['M1R', 'M9V'], ['Latitude', 'Longitude']]
gc5 = gc.loc[['M9L', 'M5V'], ['Latitude', 'Longitude']]
gc6 = gc.loc[['M1B', 'M5A'], ['Latitude', 'Longitude']]

In [7]:
initial_stack = pd.concat([gc1, gc2, gc3, gc4, gc5, gc6], axis=0)
initial_stack.reset_index(drop=True, inplace=True)

In [42]:
initial_stack

     Latitude  Longitude
0   43.657952 -79.387383
1   43.803762 -79.363452
2   43.706397 -79.309937
3   43.744734 -79.239476
4   43.709060 -79.363452
5   43.659526 -79.340923
6   43.750072 -79.295849
7   43.739416 -79.588437
8   43.756303 -79.565963
9   43.628947 -79.394420
10  43.806686 -79.194353
11  43.654260 -79.360636

In [8]:
new_stack = pd.concat([new_df, initial_stack], axis=1)

In [9]:
new_stack

,PostalCode,Borough,Neighbourhood,Latitude,Longitude
0,M5G,Downtown Toronto,Central Bay Street,43.657952,-79.387383
1,M2H,North York,Hillcrest Village,43.803762,-79.363452
2,M4B,East York,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937
3,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
4,M4G,East York,Leaside,43.709060,-79.363452
5,M4M,East Toronto,Studio District,43.659526,-79.340923
6,M1R,Scarborough,"Wexford, Maryvale",43.750072,-79.295849
7,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
8,M9L,North York,Humber Summit,43.756303,-79.565963
9,M5V,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har...",43.628947,-79.394420
10,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
11,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636